#%RAML 0.8
title: Contact API
protocols: [HTTP]

/identification:
  get:
    description: Get a list of <<resourcePathName>> based on the song title.
    responses: 
      200:
        body: 
          application/json:  
            example: |
              [{
                "firstName": "first_name",
                "lastName": "last_name",
                "dob": "2000-01-02" ,
                "gender": "M",
                "title": "Manager"
              }]
  post:
    body:
      application/json: 
        example: |
          {
            "firstName": "first_name",
            "lastName": "last_name",
            "dob": "2000-01-02" ,
            "gender": "M",
            "title": "Manager"
          }
    responses: 
      201:
  /{id}:
    get:
      responses: 
        200:
          body: 
            application/json: 
              example: |
                {
                  "firstName": "first_name",
                  "lastName": "last_name",
                  "dob": "2000-01-02" ,
                  "gender": "M",
                  "title": "Manager"
                }
    put:
    delete:
    /address:
      get:
        responses: 
          200:
            body: 
              application/json:
      post:
        responses: 
          201:
      /{addressId}:
        get:
          responses:
            200:
              body:
                application/json:
        put:
        delete:
    /communication:
      get:
        responses: 
          200:
            body: 
              application/json:
      post:
        responses: 
          201:
      /{communicationId}:
        get:
          responses:
            200:
              body:
                application/json:
        put:
        delete:
