#%RAML 0.8
title: Contact API
protocols: [HTTP]

/identification:
  get:
    responses: 
      200:
        body: 
          application/json: 
  post:
    responses: 
      201:
  /{id}:
    get:
      responses: 
        200:
          body: 
            application/json: 
    put:
    delete:
    /address:
      get:
        responses: 
          200:
            body: 
              application/json:
      post:
        responses: 
          201:
      /{addressId}:
        get:
        put:
        delete:
    /communication:
      get:
        responses: 
          200:
            body: 
              application/json:
      post:
        responses: 
          201:
      /{communicationId}:
        get:
        put:
        delete:
  
  