#%RAML 0.8
title: Contact API
protocols: HTTP

/identification:
  /{id}:
    get:
      responses: 
        200:
    post:
      responses: 
        201:
    put:
    delete:
  /address:
    get:
      responses: 
        200:
    post:
      responses: 
        201:
    put:
    delete:
  /communication:
    get:
      responses: 
        200:
    post:
      responses: 
        201:
    put:
    delete:
  
  