#%RAML 1.0 Library
usage:
   library for communication Service

types:
  communicationRequest:
    description: type for the communication
    type: communication

  communicationResponse:
    type: communication
    properties:
      communicationId:
        description: communication id
        type: integer
        required: true

  communication:
    description: object for the communication
    properties:
      type:
        description: type of communication
        type: string 
        required: true
      value:
        description: email or phone
        type: string
        required: true
      preferred:
        description: preference
        type: boolean
        required: true